[package]
name = "backup"
version = "0.1.0"
authors = ["Louis <836250617@qq.com>"]
description = "Back up your favorite online resources just like you would with git."
license = "MIT"
edition = "2021"
repository = "https://github.com/kingwingfly/backup"
documentation = ""

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# CLI
clap = { version = "4.4", features = ["derive"]}
tabled = "0.15.0"
# Error
snafu = { version = "0.8" }
# Serde
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1" }
# ProtoBuf
protobuf = { version = "3", features = ["with-bytes"] }
protobuf-json-mapping = { version = "3" }
# Tools
qrcode = { version = "0.13", default-features = false }
rand = "0.8.5"
base64 = "0.21.7"
# Net
reqwest = { version = "0.11.23", features = ["json", "cookies"] }
# Runtime
tokio = { version = "1", features = ["full"] }
# Log
tracing = { version = "0.1" }
tracing-subscriber = { version = "0.3" }


[build-dependencies]
protobuf-codegen = { version = "3" }

[features]
default = ["bili"]
bili = []
