[workspace]
members = ["fav", "fav_core", "fav_utils"]
resolver = "2"

[workspace.package]
version = "0.1.11"
authors = ["Louis <836250617@qq.com>"]
description = "Back up your favorite online resources with CLI."
license = "MIT"
edition = "2021"
repository = "https://github.com/kingwingfly/fav"
documentation = ""

[workspace.dependencies]
fav_core = { path = "fav_core" }
fav_utils = { path = "fav_utils" }

[profile.release]
lto = true
opt-level = 3
codegen-units = 1
strip = "debuginfo"
panic = "abort"
