[package]
name = "fav_core"
version = "0.0.1-alpha1"
authors.workspace = true
description = "Fav core crate; A collection of traits."
license.workspace = true
edition.workspace = true
repository.workspace = true
documentation = "https://docs.rs/fav_core"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
url = "2.5.0"
http = "1.0.0"
protobuf = { version = "3", features = ["with-bytes"] }

[build-dependencies]
rust-version = "0.4.0"
