[package]
name = "fav_utils"
version = "0.0.15"
authors.workspace = true
description = "Fav's utils crate; A collection of utilities and data structures for the fav project"
license.workspace = true
edition.workspace = true
repository.workspace = true
documentation = "https://docs.rs/fav_utils"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# core
fav_core = { workspace = true }
# CLI
indicatif = { version = "0.17", features = ["tokio"] }
# serde
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1" }
# protoBuf
protobuf = { version = "3", features = ["with-bytes"] }
protobuf-json-mapping = { version = "3" }
# net
reqwest = { version = "0.12", features = ["json", "cookies"] }
url = "2.5"
# async
tokio = { version = "1", features = [
    "macros",
    "rt-multi-thread",
    "signal",
    "process",
] }
tokio-stream = { version = "0.1" }
futures = "0.3"
# tracing
tracing = { version = "0.1" }
# tools
qrcode = { version = "0.14", default-features = false }
tempfile = "3.13.0"
sanitize-filename = "0.5.0"
md5 = "0.7.0"
unicode-width = "0.2.0"

[build-dependencies]
protobuf = { version = "3", features = ["with-bytes"] }
protobuf-codegen = { version = "3" }

[features]
default = ["bili"]
bili = []
