name: publish

on:
  workflow_dispatch:
    inputs:
      fav_derive:
        description: "publish fav_derive"
        type: boolean
        default: false
      fav_core:
        description: "publish fav_core"
        type: boolean
        default: false
      fav_utils:
        description: "publish fav_utils"
        type: boolean
        default: false
      fav_cli:
        description: "publish fav_cli"
        type: boolean
        default: false

env:
  CARGO_TERM_COLOR: always

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: install cargo components
        run: rustup component add clippy

      - name: login to crates.io
        run: cargo login ${{ secrets.CRATESIO }}

      - name: Publish packages
        run: |
          PACKAGES=("fav_derive" "fav_core" "fav_utils" "fav_cli")
          for PACKAGE in "${PACKAGES[@]}"; do
            if [[ "${{ inputs.${PACKAGE} }}" == "true" ]]; then
              .github/scripts/publish_test.sh "${PACKAGE}"
              if [[ $? -eq 0 ]]; then
                .github/scripts/publish.sh "${PACKAGE}"
              else
                echo "Tests failed for ${PACKAGE}. Skipping publishing."
              fi
            fi
          done
