name: test

on:
  pull_request:
    branches: [dev]
    types: [opened, synchronize]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Cache restore
        uses: actions/cache/restore@v3
        id: cache-cargo-restore
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ steps.extract-version.outputs.VERSION }}

      - name: Run build
        if: steps.cache-cargo-restore.outputs.cache-hit != 'true'
        run: cargo build --all-features --all-targets

      - name: Cache save
        if: steps.cache-cargo-restore.outputs.cache-hit != 'true'
        uses: actions/cache/save@v3
        id: cache-cargo-save
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ steps.cache-cargo-restore.outputs.cache-primary-key }}

      - name: run tests
      - run: .github/scripts/test.sh
